# Generated by Django 5.2.6 on 2025-09-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
        migrations.AlterModelTable(
            name='rsvp',
            table='rsvp',
        ),
    ]
