# Generated by Django 5.2.6 on 2025-10-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp_app', '0003_alter_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='confirmed',
        ),
    ]
