# Generated by Django 5.2.6 on 2025-10-18 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp_app', '0004_remove_rsvp_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
